import pandas as pd

try:
    # Her læser vi de 4 csv filer som skal redigeres ved hjælp af panda
    df1 = pd.read_csv('../../data/January-March.csv')
    df2 = pd.read_csv('../../data/April-June.csv')
    df3 = pd.read_csv('../../data/July-September.csv')
    df4 = pd.read_csv('../../data/October-December.csv')

    # Her bruger vi et dictionary til at bestemme hvilke værdier der skal erstattes i vores datasæt
    replacements = {
        'Action role-playing, first-person shooter': 'Action role-playing',
        'Action role-playing, hack and slash': 'Action role-playing',
        'Action role-playing, metroidvania': 'Action role-playing',
        'Action role-playing, sports': 'Action role-playing',
        'Action role-playing, survival horror': 'Action role-playing',
        'Action, arcade': 'Action',
        'Action, platform': 'Action',
        'Action, roguelite, platform': 'Action',
        'Action-adventure, puzzle': 'Action-adventure',
        'Action-adventure, roguelite': 'Action-adventure',
        'Action-adventure, stealth': 'Action-adventure',
        'Adventure game': 'Adventure',
        'Adventure, Survival': 'Adventure',
        'Adventure, casual': 'Adventure',
        'Adventure, puzzle': 'Adventure',
        'Adventure, rhythm': 'Adventure',
        'Adventure, visual novel': 'Adventure',
        'Aerial combat, third-person shooter': 'third-person shooter',
        'Battle royale, first-person hero shooter': 'Battle royale',
        'Board, card, strategy': 'Card Game',
        'Construction and management simulation, government simulation': 'Simulation',
        'Digital collectible card game': 'Card Game',
        'Digital collectible card game, strategy': 'Card Game',
        'Dungeon crawler, role-playing, visual novel, puzzle': 'Role-playing',
        'Fighting, party': 'Fighting',
        'Government simulation': 'Simulation',
        'Hack and slash, roguelite': 'Hack and slash',
        'Interactive novel': 'Role-playing',
        'Kart racing': 'Racing',
        'Massively multiplayer online role-playing': 'MMO',
        'Music, exercise': 'Role-playing',
        'Noir adventure': 'Adventure',
        'Photography': 'Role-playing',
        'Platform, roguelike': 'Platform',
        'Psychological horror': 'Role-playing',
        'Puzzle platformer': 'Puzzle',
        'Puzzle, adventure': 'Puzzle',
        'Puzzle, platform': 'Puzzle',
        'Puzzle, role-playing': 'Puzzle',
        'Puzzle-platform': 'Puzzle',
        'Rail shooter': 'Action',
        'Real-time strategy': 'Strategy',
        'Real-time strategy, role-playing': 'Strategy',
        'Rhythm': 'Role-playing',
        'Roguelike, deck-building': 'Strategy',
        'Roguelike, role-playing': 'Strategy',
        'Roguelite, first-person shooter': 'Strategy',
        'Role-playing, dungeon crawler': 'Role-playing',
        'Role-playing, hack and slash': 'Role-playing',
        'Role-playing, simulation': 'Role-playing',
        'Role-playing, visual novel': 'Role-playing',
        'Sandbox, adventure': 'Adventure',
        'Scrolling shooter': 'Action',
        "Shoot 'em up": 'Action',
        'Stealth': 'Role-playing',
        'Survival horror, adventure': 'Survival',
        'Survival, tactical role-playing': 'Survival',
        'Survival horror': 'Survival',
        'Tactical shooter': 'Action',
        'Train simulator': 'Simulation',
        'Visual novel, role-playing, social deduction': 'Visual novel',
        '4X, turn-based strategy': '4X',
        'Action role-playing, sandbox': 'Action role-playing',
        'Action role-playing, tower defense': 'Action role-playing',
        'Action, puzzle': 'Action',
        'Action, roguelike': 'Action',
        'Action-adventure, battle royale': 'Action-adventure',
        'Action-adventure, hack and slash': 'Action-adventure',
        'Adventure, real-time strategy': 'Adventure',
        'Battle royale, platform': 'Battle royale',
        'Battleground shooter': 'Battle royale',
        'Board, deck-building': 'Card Game',
        'Board, party': 'Card Game',
        'Bullet hell, action': 'Bullet hell',
        'Bullet hell, dungeon crawler': 'Bullet hell',
        'Business simulation game': 'Simulation',
        'Casual, sports': 'Sport',
        'City-builder, real-time strategy': 'City-building',
        'City-building, construction and management simulation': 'City-building',
        'Construction and management simulation': 'Simulation',
        'Educational': 'Simulation',
        'First-person photography': 'First-person shooter',
        'Fishing, role-playing': 'Role-playing',
        'Graphic adventure': 'Adventure',
        'Graphic adventure game': 'Adventure',
        'Hack and slash, role-playing': 'Hack and slash',
        'Horror, cooking simulator': 'Horror',
        'Horror, roguelike': 'Horror',
        'Interactive film': 'Horror',
        'Metroidvania, action': 'Action',
        'Platform, action': 'Action',
        'Platform, action role-playing': 'Action',
        'Point-and-click adventure': 'Role-playing',
        'Puzzle adventure': 'Puzzle',
        'Puzzle, action': 'Puzzle',
        'Puzzle, city-building': 'Puzzle',
        'Puzzle, strategy': 'Puzzle',
        'Racing, vehicular combat': 'Racing',
        'Rail shooter, light gun shooter': 'Action',
        'Real-time tactics, turn-based strategy': 'Role-playing',
        'Rhythm, loot shooter': 'Rhythm',
        'Roguelike deck-building': 'Roguelike',
        'Roguelike deck-building, puzzle': 'Roguelike',
        'Roguelike, action': 'Roguelike',
        'Roguelike, action role-playing': 'Roguelike',
        'Roguelike, platform': 'Roguelike',
        'Roguelite, action': 'Roguelike',
        'Roguelite, management simulation': 'Roguelike',
        'Roguelite, twin-stick shooter': 'Roguelike',
        'Role-playing video game, real-time strategy': 'Role-playing',
        'Role-playing, psychological horror': 'Role-playing',
        'Role-playing, tactical': 'Role-playing',
        'Run and gun': 'Action',
        'Sandbox, simulation': 'Simulation',
        'Shoot em up, arcade': 'Action',
        'Simulation, minigame': 'Simulation',
        'Simulator, strategy, role-playing game': 'Simulation',
        'Survival, action': 'Survival',
        'Third-person shooter, action role-playing': 'Third-person shooter',
        'Third-person shooter, first-person shooter': 'Third-person shooter',
        'Third-person shooter, survival horror': 'Third-person shooter',
        'Top-down shooter, rogue-lite': 'Top-down shooter',
        'Tower defense, action': 'Tower Defense',
        'Turn-based strategy, 4X': 'Turn-based strategy',
        'Turn-based strategy, deck-building': 'Turn-based strategy',
        'Turn-based strategy, roguelite': 'Turn-based strategy',
        'Turn-based tactics, tactical role-playing': 'Turn-based strategy',
        'Vehicle simulation': 'Simulation',
        'Action game, platform': 'Action',
        'Action role-playing, massively multiplayer online role-playing': 'Action role-playing',
        'Action role-playing, soulslike': 'Action role-playing',
        'Action role-playing, survival': 'Action role-playing',
        "Action, beat 'em up": 'Action',
        'Action, hack and slash': 'Action',
        'Action, role-playing': 'Action role-playing',
        'Action, stealth': 'Action',
        'Action, survival': 'Action',
        'Action, third-person shooter': 'Action',
        'Action-adventure, platform': 'Action-adventure',
        'Action-adventure, role-playing': 'Action-adventure',
        'Adventure, arcade': 'Adventure',
        'Adventure, role-playing': 'Adventure',
        'Adventure, survival': 'Adventure',
        "Arcade, shoot 'em up": 'Arcade',
        'Artillery, strategy': 'Strategy',
        'Brawler, battle royale': 'Battle royale',
        'Business simulation': 'Simulation',
        'Deck-building, role-playing': 'Role-playing',
        'First-person shooter, action': 'First-person shooter',
        'First-person shooter, bullet hell': 'First-person shooter',
        'First-person shooter, rhythm': 'First-person shooter',
        'First-person shooter, rhythm, roguelike': 'First-person shooter',
        'First-person shooter, roguelite': 'First-person shooter',
        'First-person shooter, stealth': 'First-person shooter',
        'Horror, visual novel': 'Horror',
        'Life simulation': 'Simulation',
        'Management simulation': 'Simulation',
        'Massively multiplayer online role-playing, sandbox': 'MMO',
        'Metroidvania, platform': 'Metroidvania',
        'Music, rhythm': 'Rhythm',
        'Narrative adventure, visual novel': 'Adventure',
        'Platform, action-adventure': 'Platform',
        'Platform, hack and slash': 'Platform',
        'Platform, visual novel': 'Platform',
        "Point-and-click adventure, beat 'em up": 'Adventure',
        'Puzzle, simulation': 'Puzzle',
        'Rhythm, action': 'Rhythm',
        'Roguelike horror, farming simulation': 'Roguelike',
        'Roguelike, adventure, sports': 'Roguelike',
        'Roguelike, auto battler': 'Roguelike',
        "Roguelike, beat 'em up": 'Roguelike',
        'Roguelite, platform': 'Roguelike',
        'Role-playing, adventure': 'Role-playing',
        'Role-playing, board game': 'Role-playing',
        'Role-playing, dungeon crawl': 'Role-playing',
        'Role-playing, interactive fiction': 'Role-playing',
        "Shoot 'em up, tower defense": 'Tower Defense',
        'Side-scrolling endless runner': 'Role-playing',
        'Simulation, role-playing': 'Simulation',
        'Social simulation': 'Simulation',
        'Strategy, simulation': 'Strategy',
        'Tower defense, roguelike': 'Tower Defense',
        'Train simulation, strategy': 'Simulation',
        'Turn-based strategy, roguelike': 'Roguelike',
        'Vehicular combat, racing': 'Racing',
        'Visual Novel, tactical role-playing': 'Visual Novel',
        'Action, first-person shooter': 'Action',
        "Action-adventure, beat 'em up": 'Action-adventure',
        'Action-adventure, survival': 'Action-adventure',
        'Adventure, art game': 'Adventure',
        'Adventure, platform': 'Adventure',
        'Adventure, sports': 'Adventure',
        "Beat 'em up, roguelite, dungeon crawler": "Beat 'em up",
        'Cinematic platform': 'Role-playing',
        'City-building, survival': 'City-building',
        'Horror adventure, visual novel': 'Horror',
        'Horror, action-adventure': 'Horror',
        'Horror, adventure': 'Horror',
        'Horror, first-person shooter': 'Horror',
        'Horror, role-playing': 'Horror',
        'Interactive drama, survival horror': 'Horror',
        'Life simulation, role-playing': 'Simulation',
        'Metroidvania, action-adventure, role-playing': 'Metroidvania',
        "Metroidvania, shoot 'em up": 'Metroidvania',
        'Party, social deduction': 'Party',
        'Pet simuatation, sandbox': 'Simulation',
        'Platform, roguelike, metroidvania': 'Platform',
        'Puzzle adventure, simulation': 'Puzzle',
        'Puzzle, Adventure': 'Puzzle',
        "Roguelike, Shoot 'em up": 'Roguelike',
        'Role-playing, social simulation': 'Role-playing',
        'Run-and-gun platform': 'Action',
        'Stealth, action': 'Action',
        'Stealth, survival horror': 'Action',
        'Strategy role-playing': 'Strategy',
        'Strategy, action role-playing': 'Strategy',
        'Survival horror, first-person shooter': 'Survival',
        'Third-person shooter, role-playing': 'Third-person shooter',
        'Turn-based strategy, adventure': 'Turn-based strategy',
        'Various': 'Adventure',
        'Visual novel, rhythm': 'Visual novel'

    }
    df1 = df1.replace(replacements)
    df2 = df2.replace(replacements)
    df3 = df3.replace(replacements)
    df4 = df4.replace(replacements)
    # Her skriver vi det nye data ind i en ny CSV fil
    df1.to_csv('../data/January-March-CLEAN.csv', index=False)
    df2.to_csv('../data/April-June-CLEAN.csv', index=False)
    df3.to_csv('../data/July-September-CLEAN.csv', index=False)
    df4.to_csv('../data/October-December-CLEAN.csv', index=False)

except FileNotFoundError:
    print("File not found. Please check the file paths.")
except pd.errors.EmptyDataError:
    print("Empty DataFrame. Please make sure the CSV files are not empty.")
except pd.errors.ParserError:
    print("Error parsing CSV file. Please check the file format.")
except Exception as e:
    print("An error occurred:", str(e))
